import type React from "react"
import type { Metadata } from "next"
import "./globals.css"
import RootLayoutClient from "./RootLayoutClient"



export const metadata: Metadata = {
  title: "Next Level | Admin-Dashboard",
  description: "Generated by create next app",
  generator: "v0.app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  )
}
